version: '3'

services:

  db:
    image: gcr.io/future-tracking/future-tracking-mysql-migrations
    container_name: db
    ports: 
      - 3306:3306
    networks:
      - net

  api:
    image: gcr.io/future-tracking/future-tracking-api
    container_name: api
    ports: 
      - 5001:80
    networks:
      - net

  app:
    image: gcr.io/future-tracking/future-tracking-app
    container_name: app
    ports: 
      - 8080:80
    networks:
      - net

networks:
  net:
    driver: bridge